#requires -Version 5.1
# Auto-generated by Claude Conversations. Runs the Claude CLI headless for a scheduled task.
$ErrorActionPreference = 'Continue'
Set-Location -Path '@@DIR@@'

# Task Scheduler starts PowerShell with the OEM codepage; force UTF-8 or Claude's
# output (and any Cyrillic) decodes into mojibake.
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding           = [System.Text.Encoding]::UTF8

$folder = '@@FOLDER@@'
$stamp  = Get-Date -Format 'yyyy-MM-dd_HHmm'
$out    = Join-Path $folder "report-$stamp.md"

$claude = (Get-Command claude -ErrorAction SilentlyContinue).Source
if (-not $claude) { $claude = "$env:USERPROFILE\.local\bin\claude.exe" }

# Read as UTF-8 explicitly: Windows PowerShell 5.1 (which Task Scheduler uses) defaults
# Get-Content to the ANSI codepage, which mangles Cyrillic/Unicode prompts into mojibake.
$prompt = Get-Content -Raw -Path (Join-Path $folder 'prompt.txt') -Encoding UTF8
if ($prompt) { $prompt = $prompt.TrimStart([char]0xFEFF) }
@@ALLOW_LINE@@

# $null | ... hands Claude an empty, already-closed stdin (skips the "no stdin" wait).
$null | & $claude -p $prompt @@ALLOW_ARG@@*>&1 | Out-File -FilePath $out -Encoding utf8
Copy-Item -Path $out -Destination (Join-Path $folder 'latest.md') -Force -ErrorAction SilentlyContinue
@@OPEN_BLOCK@@
exit 0
